spring:
  application:
    name: aisadsa-backend
  datasource:
    url: jdbc:mysql://localhost:3306/aisadsa
    username: root
    password: 8110
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    max-file-size: 10MB
    max-request-size: 10MB
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        model: gpt-4o-mini
  cloud:
    function:
      scan:
        enabled: false
server:
  port: 8080