spring:
  application:
    name: aisadsa-backend
  datasource:
    url: jdbc:mysql://localhost:3306/aisadsa
    username: root
    password: 8110
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080
  servlet:
    max-file-size: 10MB
    max-request-size: 10MB
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: "batuhan"
#    password: "batuhan"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  authentication:
#    jwt:
#      secret: aisadsa
#      expires:
#        in: 1200